version: '2'

services:

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home/

  taurus:
    image: blazemeter/taurus
    container_name: taurus
    command: performance.yml
    volumes:
      - ./build/libs/gatling-perf-1.0.0.jar:/bzt-configs/gatling-perf-1.0.0.jar
      - ./performance.yml:/bzt-configs/performance.yml
      - ./artifacts:/tmp/artifacts

