version: '3'

services:

  taurus:
    image: blazemeter/taurus
    container_name: taurus
    command: performance.yml
    volumes:
      - ./build/libs/performance-all.jar:/bzt-configs/peformance-all.jar
      - ./performance.yml:/bzt-configs/performance.yml
      - ./target/gatling/artifacts:/tmp/artifacts

#  jenkins:
#    image: jenkins/jenkins
#    container_name: jenkins
#    ports:
#    - 8081:8080
#    - 50000:50000
#    volumes:
#    - ./jenkins:/var/jenkins_home/
